version: "3.7"
services:
  db:
    image: mysql:latest
    container_name: mysql
    hostname: database
    volumes: 
        - ./database:/var/lib/mysql
        - ./provisioning.sql:/provisioning.sql
    ports: 
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  backend:
    container_name: backend 
    image: "node"
    working_dir: /home/node/PAINEL/backend
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/home/node/PAINEL/backend
    ports:
      - "3333:3333"
    command: "yarn start"
    links: 
        - db

  frontend:
      container_name: frontend
      image: "node"
      working_dir: /home/node/PAINEL/frontend
      environment:
        - NODE_ENV=production
      volumes:
        - ./frontend:/home/node/PAINEL/frontend
      ports:
        - "8080:8080"
      command: "yarn server"

