version: "3.3"
services:
    backendteste:
        image: disciplina/backend:1.0
        volumes:
            - beckend:/backend
        ports:
            - 3333:3333
        restart: always
    frontendteste:
        image: disciplina/frontend:1.0
        volumes:
            - ./config.js:/frontend/src/config.js
        ports:
            - 8080:8080
        command: >
            sh -c "yarn build &&
                   yarn server"
        depends_on:
            - backendteste
        restart: always
volumes:
    beckend:
