version: "3.1"
services:
  backend:
    ##container_name: backend 
    ##image: node:12.16.1
    ##working_dir: /home/node/PAINEL/backend
    ##volumes:
    ##  - ./backend:/home/node/PAINEL/backend
    ports:
      - "3333:3333"
    ##command: "yarn start"
    build: .
        
  frontend:
      container_name: frontend
      image: node:12.16.3
      working_dir: /home/node/PAINEL/frontend
      volumes:
        - ./frontend:/home/node/PAINEL/frontend
      ports:
        - "8080:8080"
      command: "yarn server"
      depends_on: 
          - backend
