version: "3.3"
services: 
    painel: 
        image: disciplina/painel_de_salas:1.0
        volumes: 
            - painel-ceu:/backendpainel
            - painel-ceu:/frontend
        ports: 
            - 3333:3333
        user: root
        restart: always
        
volumes:
    painel: {}