version: "3.3"
services:
  backend:
    container_name: backend
    build: ./backend
    volumes:
       - beckend:/backend 
    ports: 
       - "3333:3333"
    restart: always

  frontend:
    container_name: frontend
    build: ./frontend        
    volumes: 
        - ./config.js:/frontend/src/config.js
    ports:
        - 8080:8080
    depends_on:
            - backend
    restart: always

volumes:
    beckend:
