version: "3.3"
services: 
    backend: 
        image: disciplina/backend:1.0
        volumes: 
            - painel-ceu-backend:/backend
        ports: 
            - 3333:3333
        user: node
        restart: always
            
    frontend:
        image: disciplina/frontend:1.0
        volumes: 
            - ./config.js:/frontend/src/config.js
        ports:
            - 8080:8080
        command: > 
            sh -c "yarn build && 
                   node index.js"
        depends_on: 
            - backend
            - backendteste
        restart: always
        
volumes:
    painel-ceu-backend:
