version: "3.1"
services:
  backend:
    container_name: backend 
    build: ./backend
    ports: 
       - "3333:3333"

  frontend:
    container_name: frontend
    network_mode: host
    build:  ./frontend
    ports: 
      - "8080:8080"
    depends_on: 
          - backend
