version: "3.3"
services:
    painelbackend:
        build: ./backend
        volumes:
            - beckend:/backend
        ports:
            - 3333:3333
        restart: always
    painelfrontend:
            build: ./frontend
        volumes:
            - ./config.js:/frontend/src/config.js
        ports:
            - 8080:8080
        command: >
            sh -c "yarn build &&
                   yarn server"
        depends_on:
            - painelbackend
        restart: always
volumes:
    beckend:
