# Cria um container somente unificando as os dois projetos

version: "3.3"
services: 
    painel: 
        build: . 
        volumes: 
            - backend2:/backend
        ports: 
            - 3333:3333
        user: root
        environment: 
            LOGO: "https://jadson179.github.io/SITE-PAINEL/logo192.png"
            APP_ID: "hFc5Rx4a"
            CLIENT_ID: "dj0yJmk9aDFYd3YxaGtBZHNXJmQ9WVdrOWFFWmpOVko0TkdFbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmc3Y9MCZ4PTEy"
            CLIENT_SECRET: "4ab18573d6fdd4368f6deaa6bded2d36603a9864"
        restart: always
        
volumes:
    backend2: 
